;;; elegant-balanced-theme.el --- An elegant theme with balanced contrast for Emacs

;; Author: Generated by Claude
;; Version: 1.0
;; Keywords: faces, theme
;; Package-Requires: ((emacs "24.1"))

;;; Commentary:
;; This theme aims to be elegant with a balanced contrast level,
;; neither too dark nor too light. It uses soft colors with enough
;; contrast to ensure readability while being easy on the eyes.

;;; Code:
(deftheme elegant-black "Tema oscuro y elegante, diseñado para ser amable con la vista y avanzar con paso firme.")

(let ((class '((class color) (min-colors 89)))
      ;; Definición de la paleta de colores:
      (fg "#DCDCCC")        ;; Color principal del texto.
      (bg "#1E1E1E")        ;; Fondo principal (oscuro y elegante).
      (bg-alt "#262626")    ;; Fondo alternativo para regiones y barras.
      (cursor "#FFCC66")    ;; Color del cursor para resaltarlo.
      (red "#F2777A")
      (orange "#F99157")
      (yellow "#FFCC66")
      (green "#99CC99")
      (blue "#6699CC")
      (magenta "#CC99CC")
      (cyan "#66CCCC")
      (grey "#7F7F7F"))
  (custom-theme-set-faces
   'elegant-black

   ;; Configuración básica de colores:
   `(default ((,class (:background ,bg :foreground ,fg))))
   `(cursor ((,class (:background ,cursor))))
   `(region ((,class (:background "#3A3A3A" :foreground ,fg))))
   `(fringe ((,class (:background ,bg))))
   `(minibuffer-prompt ((,class (:foreground ,blue :weight bold))))

   ;; Resaltado de sintaxis:
   `(font-lock-builtin-face ((,class (:foreground ,magenta))))
   `(font-lock-comment-face ((,class (:foreground ,grey :slant italic))))
   `(font-lock-constant-face ((,class (:foreground ,cyan))))
   `(font-lock-function-name-face ((,class (:foreground ,blue :weight bold))))
   `(font-lock-keyword-face ((,class (:foreground ,red :weight bold))))
   `(font-lock-string-face ((,class (:foreground ,green))))
   `(font-lock-type-face ((,class (:foreground ,yellow))))
   `(font-lock-variable-name-face ((,class (:foreground ,orange))))
   `(font-lock-warning-face ((,class (:foreground ,red :background ,bg-alt :weight bold))))

   ;; Configuración de la barra de modo (mode-line):
   `(mode-line ((,class (:foreground ,fg :background ,bg-alt
                          :box (:line-width -1 :style released-button)))))
   `(mode-line-inactive ((,class (:foreground ,grey :background ,bg
                                   :box (:line-width -1 :style released-button)))))
   `(header-line ((,class (:foreground ,fg :background ,bg-alt))))

   ;; Otros elementos de la interfaz:
   `(link ((,class (:foreground ,blue :underline t))))
   `(show-paren-match ((,class (:background ,blue :foreground ,bg :weight bold))))
   `(show-paren-mismatch ((,class (:background ,red :foreground ,bg :weight bold))))
   ))

(provide-theme 'elegant-black)
;;; elegant-black-theme.el ends here
;;; elegant-balanced-theme.el ends here
